# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 07:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('img', models.ImageField(blank=True, upload_to='images', verbose_name='Изборажение (не обязательно)')),
            ],
            options={
                'verbose_name_plural': 'Обо мне/главная страница',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Заголовок')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст')),
                ('img', models.ImageField(blank=True, upload_to='images', verbose_name='Изборажение (не обязательно)')),
            ],
            options={
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('img', models.ImageField(upload_to='images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название экскурсии')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='images', verbose_name='Изборажение (не обязательно)')),
            ],
            options={
                'verbose_name_plural': 'Список экскурсий',
            },
        ),
        migrations.CreateModel(
            name='ImportantNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Важное сообщение на главной странице')),
            ],
            options={
                'verbose_name_plural': 'Важное сообщение на главной странице',
            },
        ),
        migrations.CreateModel(
            name='PeopleReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер теллефона')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excursion', models.CharField(max_length=50, verbose_name='Экскурсия')),
                ('event_date', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex.Excursion'),
        ),
    ]
