# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_excursion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение'),
        ),
    ]
