# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 21:10
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_auto_20161217_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='f', max_length=50),
            preserve_default=False,
        ),
    ]
