# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0005_auto_20161218_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='peoplereg',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Номер телефона'),
        ),
    ]
