# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0010_peoplereg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='event_date',
            field=models.DateField(verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.TextField(verbose_name='Отзыв'),
        ),
    ]
