# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-31 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0011_auto_20161231_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('likes', models.IntegerField(default=0, editable=False)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Заметки',
            },
        ),
        migrations.AlterModelOptions(
            name='peoplereg',
            options={'verbose_name_plural': 'Зарегистрировавшиеся'},
        ),
    ]
