# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 23:12
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0012_auto_20161231_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportantNote',
        ),
        migrations.AlterField(
            model_name='blog',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание'),
        ),
    ]
