# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0013_auto_20170117_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='event_date',
            field=models.DateField(verbose_name='Дата посещения11'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='excursion',
            field=models.CharField(max_length=50, verbose_name='Экскурсия11'),
        ),
    ]
