# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0014_auto_20170119_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplereg',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время1'),
        ),
    ]
