# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0017_auto_20170119_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionImageStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex.Excursion')),
            ],
            options={
                'verbose_name_plural': 'Изображения для экскурсий',
            },
        ),
    ]
