# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0018_excursionimagestorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionimagestorage',
            name='img_alt',
            field=models.CharField(blank=True, max_length=50, verbose_name='Описание изображения(опционально)'),
        ),
    ]
